# Generated by Django 4.2.5 on 2023-09-23 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Место, в котором необходимо выполнять привычку.', max_length=150, verbose_name='Место')),
                ('time', models.TimeField(default=django.utils.timezone.now, help_text='Время, когда необходимо выполнять привычку.', verbose_name='Время')),
                ('action', models.CharField(help_text='Действие, которое представляет из себя привычка.', max_length=150, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Привычка, которую можно привязать к выполнению полезной привычки', verbose_name='Признак приятной привычки')),
                ('reward', models.CharField(blank=True, help_text='Чем пользователь должен себя вознаградить после выполнения.', max_length=150, null=True, verbose_name='Вознаграждение ')),
                ('frequency', models.PositiveIntegerField(default=1, help_text='Периодичность выполнения привычки для напоминания в днях (по умолчанию ежедневная)', verbose_name='Периодичность')),
                ('duration', models.PositiveIntegerField(default=120, help_text='Время, которое предположительно потратит пользователь на выполнение привычки.', verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, help_text='Привычки можно публиковать в общий доступ, чтобы другие пользователи могли брать в пример чужие привычки.', verbose_name='Признак публичности')),
                ('link_pleasant', models.ForeignKey(blank=True, help_text='Привычка, которая связана с другой привычкой, важно указывать для полезных привычек, но не для приятных.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
